# Site settings
title: Rhino AEC Documentation
# email: alain@mcneel.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mcneel.github.io/architecture-guide/" # the base hostname & protocol for your site
nwo: "mcneel/architecture-guide" # github repository (name with owner)
# twitter_username: ""
github_username:  mcneel

# theme: jekyll-theme-minimal


# RhinoScriptSyntax API docs
rss_show_bad_docstring: true
rss_show_missing_examples_links: false

# Build settings
#markdown: redcarpet

# If we decide that we want to use kramdown over redcarpet, syntax
# highlighting is performed by turning on the following options and
# including/running highlight.js (https://highlightjs.org/) at the
# top of pages that need it (probably just add to head.html)
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

#port: 4444

safe: true

collections:
 - en

collections:
  en:
    output: true
    permalink: /en/:path
